[twitter]
        # Enter your secrets here. See README.md for more info.
        consumer_key = 'wf1d0p0JsDh4yDfcizj7xYACo'
        consumer_secret = 'em8Oix6Th3A6bY71FPc89DuzADp6YpyvCmXgIYOIeKXCftNraO'