[twitter]
        # Enter your secrets here. See README.md for more info.
        consumer_key = 'dCCMPGepRml8XwTuIjAAvnaPx'
        consumer_secret = 'T0eTzgftm17WHwLVIVTGOBf5cMeo2FBsQqitS7SR8d2mSyuzbP'